### ISSUE TITLE
Combine 2013, 2014, 2015 data into a single spreadsheet

### ISSUE THREAD

**Issue by psiemens** [ubyssey/salarydb#6]
We need to combine the data from all three years into a single document so that everything is in one place.

**Data to be merged:**
- 2013/14 salaries (already formatted + sanitized)
- 2014/15 salaries (in Excel format, needs to be converted to same format as 2013/14 data)
- 2015/16 salaries (in PDF format, see #5)

The data files can be found here: https://drive.google.com/open?id=0B4JErCL5dt7GME1uSVAtc3NQNm8

Once these datasets are merged, we can change the database schema to reflect the new format.

To give you an idea for how the data should be combined, we'll basically be turning this:

![screen shot 2017-02-02 at 3 04 53 pm](https://cloud.githubusercontent.com/assets/2547035/22572449/074aea70-e959-11e6-8ea6-c57160c89a8b.png)

into something like this:

![screen shot 2017-02-02 at 3 07 18 pm](https://cloud.githubusercontent.com/assets/2547035/22572521/5cffb432-e959-11e6-9323-f3af9fba6325.png)

**Comment by Cesium-Ice** [comment]
@psiemens 
Merged! The data for 2015 is missing the position and department, I haven't filled in that data because there are 500 entries and I didn't want to spend the next 8 hours looking things up on the internet. Perhaps finding a more efficient way to do that could be another task? Or maybe you could ask for a version of the data with that information included?

[salaries_combined.xlsx](https://github.com/ubyssey/salarydb/files/759650/salaries_combined.xlsx)

**Comment by psiemens** [comment]
Woo! Thanks @Cesium-Ice
